config/routes.rb
Hogwarts::Application.routes.draw do

  root "houses#index"
  resources :houses, only: [:index, :show]
  resources :students, only: [:index, :show]

end

app/models/house.rb
class House < ActiveRecord::Base
  has_many :students
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :house
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController

  def index
    @houses = House.all
  end

  def show
    @house = House.find(params[:id])
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/houses/index.html.erb
<h1>The Houses</h1>
<% @houses.each do |house| %>
  <div class="house">

    <h2><%= link_to house.name, house_path(house, :id => house.id) %></h2>
    <img src="<%= house.image_url %>"/>

  </div>
    <% end %>

app/views/houses/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @house.name %>
</p>

<img src="<%= @house.image_url %>">

<p><%= link_to 'back', houses_path %></p>

<% @house.students.each do |student| %>
  <div class="student">
    <h2><%= student.name %></h2>

    <img src="<%= student.img_url %>">
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <title>Hogwarts</title>
  </head>
  <body>
    <nav>
      <h1>Welcome to Hogwarts!</h1>
      <h2><%= link_to "View Houses", houses_path %> | <%= link_to "View Students", students_path %> | <%= link_to "Enroll", students_path %></h2>
    </nav>

    <%= yield %>

  </body>
</html>

app/views/students/index.html.erb
<h1>Hogwarts Students</h1>
<% @students.each do |student| %>
  <div>
    <%= link_to 'student', student_path(student) %> - <%= student.house %>
<% end %>
  </div>

app/views/students/new.html.erb
<h1>Welcome to the Sorting Hat!</h1>
<%= image_tag "http://flavorwire.files.wordpress.com/2009/06/sorting-hat.jpg" %>

<%= form_for @student do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :img_url %>
  <%= f.text_field :img_url %>

  <%= f.submit "Enroll" %>
<% end %>

app/views/students/show.html.erb
<h1><%= student.name %></h1>
<h2><%= student.house %></h2>
<div class="student">
<img src="<%= student.img_url %>">
</div>